"""End-to-end example: reproduce Binsec's official ``magic`` quickstart.

The original challenge and SSE script live in the binsec/binsec Docker
image at /home/binsec/examples/sse/quickstart. The script we mimic is::

    starting from <magic>
    esp := 0xffffccf1
    return_address<32> := 0x0804812b
    @[esp, 4] := return_address
    arg<32> := @[esp + 4, 4]
    reach return_address such that al <> 0 then print arg
    cut at return_address

The aim of the challenge is: find the integer ``arg`` such that the
``magic(arg)`` function returns true (al non-zero on x86-32 cdecl).

Expected output::

    [sse:result] Value arg<32> : 0xc0dedead

Prerequisites:
    - ``binsec`` available (on PATH or via PYBINSEC_BINARY)
    - the ``magic`` binary from binsec/binsec/examples/sse/quickstart

Usage::

    python examples/01_sse_magic.py /path/to/magic

Implementation notes
--------------------
We faithfully reproduce the official script with one small caveat: our
:func:`ScriptBuilder.reach` and :func:`ScriptBuilder.cut_at` only accept
addresses (int / symbol string / ``Sym``), not typed variables, so the
``reach return_address`` line of the original is rewritten as
``reach 0x0804812b``. The behaviour is identical because the official
script binds ``return_address`` to that exact value one line earlier.

This shows up as a limitation candidate for a future API tweak: allow
``Var(name, size)`` as the address argument so the script reads more
literally. For now, raw integers do the job.
"""

from __future__ import annotations

import sys

from pybinsec import Binsec, ScriptBuilder, SSERunner

# Addresses lifted from the binary in the official image. They are
# stable across rebuilds because the binary is committed as-is in the
# binsec repo (it is not regenerated by their CI).
_MAGIC_ENTRY = 0x0804805C  # not used directly, kept for reference; we
# enter via the symbol '<magic>'
_RETURN_ADDR = 0x0804812B  # arbitrary post-magic address used as the
# "return target" we want SSE to reach


def main(binary_path: str) -> int:
    bs = Binsec()
    print(f"[+] Using {bs.path} ({bs.info.version})")

    # Build the script in the same order as the official crackme.ini
    # so that the comparison is line-by-line obvious.
    script = (
        ScriptBuilder()
        .starting_from("magic")  # entry by symbol, not address
        .init("esp", 0xFFFFCCF1)  # arbitrarily concretize the stack pointer
        # The "return address" is declared as a typed variable so it
        # can be referenced by name later. This is purely a readability
        # gain; SSE will substitute its concrete value at use sites.
        .init("return_address", _RETURN_ADDR, size=32)
        # Push the return address on the stack so the function ret
        # would land where we want.
        .init_memory("esp", "return_address", size=4)
        # Capture the function argument (passed via the stack on x86-32
        # cdecl) into a named typed variable. The reach/print clause
        # below will then dump ``arg`` directly.
        .init("arg", "@[esp + 4, 4]", size=32)
        # Reach the post-magic point only on the path where the
        # function returned true (al != 0 in x86-32 cdecl), and have
        # binsec print the captured argument.
        .reach(_RETURN_ADDR, such_that="al <> 0", then="print arg")
        .cut_at(_RETURN_ADDR)
        .build()
    )

    print("[+] SSE script:")
    for line in script.to_sse().splitlines():
        print(f"      {line}")

    runner = SSERunner(bs)
    result = runner.run(script, binary_path, timeout=60)

    print(f"[+] Exit code: {result.returncode}")
    print(f"[+] Reached:   {len(result.reached)} point(s)")
    for rp in result.reached:
        sym = f" ({rp.symbol})" if rp.symbol else ""
        print(f"      path {rp.path_id} at 0x{rp.address:x}{sym}")
        for k, v in rp.values.items():
            print(f"        {k} = 0x{v:x}")
    print(f"[+] Cuts:      {len(result.cuts)}")

    # Quick sanity check: was the secret recovered?
    expected = 0xC0DEDEAD
    for rp in result.reached:
        if rp.values.get("arg<32>") == expected:
            print(f"[+] Secret recovered: arg<32> = 0x{expected:x}")
            return 0
    print(f"[!] Secret NOT recovered (expected 0x{expected:x})", file=sys.stderr)
    return 1


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <binary>", file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
